<?php  //[STAMP] 768b14669a7b38cca9fec0163ba559c0
namespace bc\rest\tests\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

use bc\rest\tests\Helper\Components;

trait ComponentsTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
