<?php  //[STAMP] 3c20b9f0a4994efc95edd5416555c81a
namespace bc\rest\tests\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

use bc\rest\tests\Helper\Extensions;

trait ExtensionsTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
