<?php  //[STAMP] 12abd1b355551e3b861a803d80cb3b04
namespace bc\rest\tests\_generated;

// This class was automatically generated by build task
// You should not change it manually as it will be overwritten on next build
// @codingStandardsIgnoreFile

use bc\rest\tests\Helper\Generator;

trait GeneratorTesterActions
{
    /**
     * @return \Codeception\Scenario
     */
    abstract protected function getScenario();

    
}
